### ISSUE TITLE
Migrate to reading from NAND title

### ISSUE THREAD

**Issue by spotlightishere** [ramblecube/osc-downloader#1]
For SD card-based homebrew titles, our current design involves a hidden title being utilized to download our homebrew software’s zip file.

We plan to modify this application to perform the following:
 - [x] read from ec.cfg a title ID
 - [x] read the primary content, ID or index zero, from our hidden SD title
 - [x] replace the contents of our SD title with a zero-length file, editing the TMD appropriately
 - [x] opening the Wii Shop Channel upon completion

**Comment by spotlightishere** [comment]
Complete as of 3e9b06204707b4393713b8fc241eac2d8c8e01be.

**Comment by ramblecube** [comment]
> For SD card-based homebrew titles, our current design involves a hidden title being utilized to download our homebrew software’s zip file.
> 
> We plan to modify this application to perform the following:
> 
>     * [x]  read from ec.cfg a title ID
> 
>     * [x]  read the primary content, ID or index zero, from our hidden SD title
> 
>     * [x]  replace the contents of our SD title with a zero-length file, editing the TMD appropriately
> 
>     * [x]  opening the Wii Shop Channel upon completion

Was reading this and unchecked a checkbox on accident. If you got a notification- my bad!
